@extends("temp_back")
@section("link")
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
{{-- <style type="text/css">
@keyframes ldio-c7tw2yj0lkg {
  0% { transform: rotate(0deg) }
  100% { transform: rotate(360deg) }
}
.ldio-c7tw2yj0lkg > div > div {
  transform-origin: 100px 100px;
  animation: ldio-c7tw2yj0lkg 3.0303030303030303s linear infinite;
  opacity: 0.8
}
.ldio-c7tw2yj0lkg > div > div > div {
  position: absolute;
  left: 30px;
  top: 30px;
  width: 70px;
  height: 70px;
  border-radius: 70px 0 0 0;
  transform-origin: 100px 100px
}.ldio-c7tw2yj0lkg > div div:nth-child(1) {
  animation-duration: 0.7575757575757576s
}
.ldio-c7tw2yj0lkg > div div:nth-child(1) > div {
  background: #93dbe9;
  transform: rotate(0deg);
}.ldio-c7tw2yj0lkg > div div:nth-child(2) {
  animation-duration: 1.0101010101010102s
}
.ldio-c7tw2yj0lkg > div div:nth-child(2) > div {
  background: #689cc5;
  transform: rotate(0deg);
}.ldio-c7tw2yj0lkg > div div:nth-child(3) {
  animation-duration: 1.5151515151515151s
}
.ldio-c7tw2yj0lkg > div div:nth-child(3) > div {
  background: #5e6fa3;
  transform: rotate(0deg);
}.ldio-c7tw2yj0lkg > div div:nth-child(4) {
  animation-duration: 3.0303030303030303s
}
.ldio-c7tw2yj0lkg > div div:nth-child(4) > div {
  background: #3b4368;
  transform: rotate(0deg);
}
.loadingio-spinner-wedges-68w6k6xjuws {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: #ffffff;
}
.ldio-c7tw2yj0lkg {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-c7tw2yj0lkg div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style> --}}
<style type="text/css">
@keyframes ldio-ie6gnmfxvts-1 {
    0% { transform: rotate(0deg) }
   50% { transform: rotate(-45deg) }
  100% { transform: rotate(0deg) }
}
@keyframes ldio-ie6gnmfxvts-2 {
    0% { transform: rotate(180deg) }
   50% { transform: rotate(225deg) }
  100% { transform: rotate(180deg) }
}
.ldio-ie6gnmfxvts > div:nth-child(2) {
  transform: translate(-15px,0);
}
.ldio-ie6gnmfxvts > div:nth-child(2) div {
  position: absolute;
  top: 43.4px;
  left: 43.4px;
  width: 130.2px;
  height: 65.1px;
  border-radius: 130.2px 130.2px 0 0;
  background: #fad96d;
  animation: ldio-ie6gnmfxvts-1 1s linear infinite;
  transform-origin: 65.1px 65.1px
}
.ldio-ie6gnmfxvts > div:nth-child(2) div:nth-child(2) {
  animation: ldio-ie6gnmfxvts-2 1s linear infinite
}
.ldio-ie6gnmfxvts > div:nth-child(2) div:nth-child(3) {
  transform: rotate(-90deg);
  animation: none;
}@keyframes ldio-ie6gnmfxvts-3 {
    0% { transform: translate(206.15px,0); opacity: 0 }
   20% { opacity: 1 }
  100% { transform: translate(75.95px,0); opacity: 1 }
}
.ldio-ie6gnmfxvts > div:nth-child(1) {
  display: block;
}
.ldio-ie6gnmfxvts > div:nth-child(1) div {
  position: absolute;
  top: 99.82px;
  left: -8.68px;
  width: 17.36px;
  height: 17.36px;
  border-radius: 50%;
  background: #959795;
  animation: ldio-ie6gnmfxvts-3 1s linear infinite
}
.ldio-ie6gnmfxvts > div:nth-child(1) div:nth-child(1) { animation-delay: -0.67s }
.ldio-ie6gnmfxvts > div:nth-child(1) div:nth-child(2) { animation-delay: -0.33s }
.ldio-ie6gnmfxvts > div:nth-child(1) div:nth-child(3) { animation-delay: 0s }
.loadingio-spinner-bean-eater-wu14xy8asa9 {
  width: 217px;
  height: 217px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-ie6gnmfxvts {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-ie6gnmfxvts div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>
    
    
    <link rel="stylesheet" href="{{URL::asset('css/offcanvas.css')}}">
@stop
@section("class") 
class="bg-light"
@stop
@section("content") 
  
<!-- Modal 載入動畫-->
<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">檔案上傳中</h5>
       
      </div>
      <div class="modal-body"style="text-align:center;">
<div class="loadingio-spinner-bean-eater-wu14xy8asa9"><div class="ldio-ie6gnmfxvts">
<div><div></div><div></div><div></div></div><div><div></div><div></div><div></div></div>
</div></div>
      </div>
      <div class="modal-footer">
       
      </div>
    </div>
  </div>
</div>  


<main class="container">
  <div class="d-flex justify-content-center  p-3 my-3 text-white bg-purple rounded shadow-sm">
    <div class="lh-1">
      <h1 class="h6 mb-0 text-white lh-1"><i class="fas fa-file-upload fa-2x"></i>  院系科自訂表檔案上傳</h1>
    </div>
  </div>

  <div class="my-3 p-3 bg-body rounded shadow-sm">
    <h6 class="border-bottom pb-2 mb-0 text-center">院系科表上傳</h6>
    <div class="d-flex text-muted pt-3">
      <p class="pb-3 mb-0 small lh-sm border-bottom w-100">
        <strong class="d-block text-gray-dark">檔案下載</strong>
        <a href="https://udb.moe.edu.tw/udata/DetailReportList/%E5%AD%B8%E7%94%9F%E9%A1%9E"target="_blank">點此連結下載欲更新年度資料,請選擇【學1-1】以XLSX檔下載</a>
      </p>
    </div>


    <div class="d-flex text-muted pt-3 border-bottom w-100">
      <form method="post" action="{{route('College_System_from')}}"enctype="multipart/form-data">
        @csrf
       <div class="mb-3">
         <label for="formFileSm" class="form-label">選擇檔案</label>
         <input name="file" class="form-control form-control-sm" id="formFileSm" type="file">
       </div>
    </div>

       <small class="d-block text-end mt-3">
          <button type="submit" class="btn btn-outline-success"data-bs-toggle="modal" data-bs-target="#staticBackdrop">送出</button>
        </small>
      </form>
  </div>



       <div class="my-3 p-3 bg-body rounded shadow-sm">
    <h6 class="border-bottom pb-2 mb-0 text-center">休退學院系科表上傳</h6>
    <div class="d-flex text-muted pt-3">
      <p class="pb-3 mb-0 small lh-sm border-bottom w-100">
        <strong class="d-block text-gray-dark">檔案下載</strong>
        <a href="https://udb.moe.edu.tw/udata/DetailReportList/%E5%AD%B8%E7%94%9F%E9%A1%9E"target="_blank">點此連結下載欲更新年度資料,請選擇【學13-1】以XLSX檔下載</a>
      </p>
    </div>


    <div class="d-flex text-muted pt-3 border-bottom w-100">
      <form method="post" action="{{route('DSP_System_from')}}"enctype="multipart/form-data">
        @csrf
       <div class="mb-3">
         <label for="formFileSm" class="form-label">選擇檔案</label>
         <input name="file" class="form-control form-control-sm" id="formFileSm" type="file">
       </div>
    </div>

       <small class="d-block text-end mt-3">
          <button type="submit" class="btn btn-outline-success"data-bs-toggle="modal" data-bs-target="#staticBackdrop">送出</button>
        </small>
      </form>
  </div>


  <div class="my-3 p-3 bg-body rounded shadow-sm">
    <h6 class="border-bottom pb-2 mb-0 text-center">教師院系科編輯表</h6>
    <div class="d-flex text-muted pt-3">
      <p class="pb-3 mb-0 small lh-sm border-bottom w-100">
        <strong class="d-block text-gray-dark">檔案下載</strong>
        <a href="https://udb.moe.edu.tw/udata/DetailReportList/%E6%95%99%E8%81%B7%E9%A1%9E"target="_blank">點此連結下載欲更新年度資料,請選擇【教1-1】以XLSX檔下載</a>
      </p>
    </div>


    <div class="d-flex text-muted pt-3 border-bottom w-100">
      <form method="post" action="{{route('Teacher_System_from')}}"enctype="multipart/form-data">
        @csrf
       <div class="mb-3">
         <label for="formFileSm" class="form-label">選擇檔案</label>
         <input name="file" class="form-control form-control-sm" id="formFileSm" type="file">
       </div>
    </div>

       <small class="d-block text-end mt-3">
          <button type="submit" class="btn btn-outline-success"data-bs-toggle="modal" data-bs-target="#staticBackdrop">送出</button>
        </small>
      </form>
 </div>




</main>
@stop

  @section("script")
  <script  src="{{URL::asset('js/offcanvas.js')}}"></script>
@stop
